version: '3.7'

services:

  frontend:
    build: .
    container_name: frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    