version: '3.2'
services:
   frontend:
     build: ./FrontEnd
     image: frontend_image
     container_name: bookingapi_frontend
     ports:
        - 3000:3000
     environment:
        - CHOKIDAR_USEPOLLING=true
     stdin_open: true
     depends_on: 
         - backend
    
   backend:
      build: ./BackEnd
      image: backend_image
      container_name: bookingapi_backend
      environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bookingapi_db?useLegacyDatetimeCode=false&serverTimezone=UTC
         SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
      ports:
         - 8080:8080
      depends_on: 
        - database

   database:
     restart: always
     container_name: bookingapi_mysql
     image: mysql:latest
     ports:
        - 6033:3306
     volumes:
        - mysql-datavolume:/var/lib/mysql
     environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=bookingapi_db
    
volumes:
  mysql-datavolume: