version: 2.0
jobs:
  build_backend:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/repofiles/BackEnd 
      
    steps:
      - checkout:
          path: ~/repofiles
      - restore_cache:
          keys:
            - bookingapi-dependencies-{{ checksum "pom.xml" }}

      - run: ./mvnw dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: bookingapi-dependencies-{{ checksum "pom.xml" }}
      - run: ./mvnw package -Dmaven.test.skip=true
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/bookingAPI-0.0.1-SNAPSHOT.jar
          
#  test:
#    docker:
#      - image: circleci/openjdk:8-jdk-stretch
#      
#    working_directory: ~/repofiles/BackEnd
#    
#    steps:
#      - run: ls
    
          
workflows:
  build-and-deploy:
    jobs:
      - build_backend:
      filters:
        branches:
          only: master