version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      restart: always
      container_name: bookingapi_mysql
      image: mysql:latest
      ports:
        - 6033:3306
      volumes:
        - mysql-datavolume:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=bookingapi_db