# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      build:
        docker:
         - image:  "circleci/node:13.11.0"
            
        working_directory: ~/repofiles/FrontEnd
          
        steps:
          - checkout:
              path: ~/repofiles
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            
          - run: npm install
    
          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
            
          - run: npm test