INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (1, 'admin', 'password', 'ROLE_ADMIN')
INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (2, 'employee', 'password', 'ROLE_EMPLOYEE')
INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (3, 'customer', 'password', 'ROLE_CUSTOMER')

