INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (1, 'admin', 'password', 'ADMIN')
INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (2, 'employee', 'password', 'EMPLOYEE')
INSERT INTO USER (ID, USERNAME, PASSWORD, AUTH_GROUP) VALUES (3, 'customer', 'password', 'CUSTOMER')

